const mongoose = require("mongoose");

const Component = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    enum: [
      "Resistor 10KΩ",
      "Capacitor 100nF",
      "Transistor BC547",
      "Diodo 1N4007",
      "LED Azul 5mm",
      "Microcontrolador ESP32",
      "Regulador de Tensão LM7805",
      "Potenciômetro 10KΩ",
      "Sensor de Temperatura LM35",
      "Display OLED 128x64",
      "Cristal Oscilador 16MHz",
      "Indutor 100µH",
      "Placa Wi-Fi ESP8266",
      "Conversor DC-DC Step Down",
      "Amplificador Operacional LM358",
      "Relé 5V 10A",
      "Fonte Chaveada 12V 2A",
      "Sensor de Umidade DHT22",
      "CIs Lógico 74HC595",
      "Buzzer Piezoelétrico",
      "Chave Táctil 6x6mm",
      "Módulo Bluetooth HC-05",
      "Ponte H L298N",
      "Sensor Ultrassônico HC-SR04",
      "Conversor USB-TTL CP2102",
      "Eletrolítico 470µF 16V",
      "Sensor de Luz LDR",
      "MOSFET IRFZ44N",
      "Sensor de Corrente ACS712",
      "Display LCD 16x2 I2C",
      "Resistor de Precisão 1% 1KΩ",
      "Módulo GPS NEO-6M",
      "Acoplador Óptico PC817",
      "Memória EEPROM 24C256",
      "Encoder Rotativo KY-040",
      "Bateria Li-Ion 18650",
      "Módulo RFID RC522",
      "Diodo Zener 5.1V",
      "Triac BT136",
      "Fonte Step-Up XL6009",
      "Ponte Retificadora DB107",
      "Placa Sensor de Chama",
      "Sensor de Pressão BMP280",
      "RTC DS3231 (Relógio de Tempo Real)",
      "Microfone Eletrético",
      "Módulo Relé de Estado Sólido",
      "Célula de Carga 5Kg",
      "Sensor de Gás MQ-2",
      "Módulo PWM PCA9685",
      "Sensor de Inclinação SW-520D",
    ],
  },
  type: { type: String, required: true, enum: ['Resistor', 'Capacitor', 'Microcontrolador'] },
  specifications: {
    type: String,
    required: true,
    enum: ["Resistência", "Capacitância", "Modelo"],
  },
  board: { type: mongoose.Schema.ObjectId, ref: "Board" },
});

module.exports = mongoose.model("Component", Component);
